src/Entity/Customer.php
<?php

namespace App\Entity;

use App\Repository\CustomerRepository;
use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Entity(repositoryClass=CustomerRepository::class)
 */
class Customer
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    public $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Age;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Phone;




    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->Address;
    }

    public function setAddress(string $Address): self
    {
        $this->Address = $Address;

        return $this;
    }

    public function getAge(): ?string
    {
        return $this->Age;
    }

    public function setAge(string $Age): self
    {
        $this->Age = $Age;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->Phone;
    }

    public function setPhone(string $Phone): self
    {
        $this->Phone = $Phone;

        return $this;
    }



}

src/Controller/CustomerController.php
<?php

namespace App\Controller;


use App\Entity\Customer;
use App\Form\CustomerAddType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CustomerController extends AbstractController
{
    /**
     * @Route("/customer", name="customer_list")
     */
    public function listAction()
    {
        $customer = $this->getDoctrine()
            ->getRepository(customer::class)
            ->findAll();
        return $this->render('customer/index.html.twig', [
            'customer' => $customer
        ]);
    }
    /**
     * @Route("/customer/view/{id}", name="customer_view")
     */
    public function detailsAction($id)
    {
        $customer = $this->getDoctrine()
            ->getRepository(customer::class)
            ->find($id);

        return $this->render('customer/view.html.twig', [
            'customer' => $customer
        ]);
    }
    /**
     * @Route("/customer/delete/{id}", name="customer_delete")
     */
    public function deleteAction($id)
    {
        $em = $this->getDoctrine()->getManager();
        $customer = $em->getRepository(customer::class)->find($id);
        $em->remove($customer);
        $em->flush();

        $this->addFlash(
            'error',
            'Customer delete success'
        );

        return $this->redirectToRoute('customer_list');
    }
    /**
     * @Route("/customer/create", name="customer_create", methods={"GET","POST"})
     */
    public function createAction(Request $request)
    {
        $customer = new customer();
        $form = $this->createForm(CustomerAddType::class, $customer);

        if ($this->saveChanges($form, $request, $customer)) {
            $this->addFlash(
                'notice',
                'Customer Add success'
            );

            return $this->redirectToRoute('customer_list');
        }

        return $this->render('customer/create.html.twig', [
            'form' => $form->createView()
        ]);
    }

    public function saveChanges($form, $request, $customer)
    {
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $em = $this->getDoctrine()->getManager();
            $em->persist($customer);
            $em->flush();

            return true;
        }
        return false;
    }
    /**
     * @Route("/customer/update/{id}", name="customer_update")
     */
    public function updateAction($id, Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $customer = $em->getRepository(customer::class)->find($id);

        $form = $this->createForm(CustomerAddType::class, $customer);

        if ($this->saveChanges($form, $request, $customer)) {
            $this->addFlash(
                'notice',
                'Customer update success'
            );
            return $this->redirectToRoute('customer_list');
        }

        return $this->render('customer/update.html.twig', [
            'form' => $form->createView()
        ]);
    }

}

templates/customer/create.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    {{ form_start(form) }}
    <div class="form-group">
        <label for="name">Name:</label>
        {{ form_widget(form.Name,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Name'
            }
        }) }}
        <div class="invalid-feedback">
            {{ form_errors(form.Name) }}
        </div>
    </div>
    <div class="form-group">
        <label for="category">Address:</label>
        {{ form_widget(form.Address,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Address'
            }
        }) }}
    </div>
    <div class="form-group">
        <label for="description">Age:</label>
        {{ form_widget(form.Age,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Age'
            }
        }) }}
    </div>
    <div class="form-group">
        <label for="priority">Phone:</label>
        {{ form_widget(form.Phone,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Phone'
            }
        }) }}
    </div>

    <input type="submit" name="create_customer" value="Create" class="btn btn-primary"/>
    {{ form_end(form) }}
{% endblock %}

templates/customer/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="bs-example" data-example-id="striped-table">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Customer</th>
                <th>Address</th>
                <th>Age</th>
                <th>Phone</th>
            </tr>
            </thead>
            <tbody>
            {% for customer in customer %}
                <tr>
                    <th scope="row">{{ customer.id }}</th>
                    <td>{{ customer.name }}</td>
                    <td>{{ customer.address }}</td>
                    <td>{{ customer.age }}</td>
                    <td>{{ customer.phone }}</td>
                    <td>
                        <a href="{{ path('customer_view', {'id': customer.id}) }} " class='btn btn-success'>View</a>
                        <a href="{{ path('customer_update', {'id': customer.id}) }}" class='btn btn-default'>Update</a>
                        <a href="{{ path('customer_delete', {'id': customer.id}) }}" class='btn btn-danger'>Delete</a>


                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <a href="{{ path('customer_create') }}" class="btn btn-primary">Create new</a>
{% endblock %}

templates/customer/update.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {{ form_start(form) }}
    <div class="form-group">
        <label for="name">Name:</label>
        {{ form_widget(form.Name,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Name'
            }
        }) }}
    </div>
    <div class="form-group">
        <label for="category">Address:</label>
        {{ form_widget(form.Address,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Address'
            }
        }) }}
    </div>
    <div class="form-group">
        <label for="description">Age:</label>
        {{ form_widget(form.Age,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Age'
            }
        }) }}
    </div>
    <div class="form-group">
        <label for="priority">Phone:</label>
        {{ form_widget(form.Phone,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Phone'
            }
        }) }}
    </div>

    <input type="submit" name="Update_customer" value="Update" class="btn btn-primary"/>
    {{ form_end(form) }}
{% endblock %}

templates/customer/view.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <a href="{{ path('customer_list') }}" class="btn btn-default">Back to Customer List</a>
    <hr/>
    <h2 class="page-header">{{ customer.name }}</h2>
    <ul class="list-group">
        <li class="list-group-item">Address: {{ customer.address }}</li>
        <li class="list-group-item">Age: {{ customer.age }}</li>
        <li class="list-group-item">Phone: {{ customer.phone }}</li>
    </ul>

{% endblock %}