src/Entity/Shoes.php
<?php

namespace App\Entity;

use App\Repository\ShoesRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ShoesRepository::class)
 */
class Shoes
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Category;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Supplier;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->Category;
    }

    public function setCategory(string $Category): self
    {
        $this->Category = $Category;

        return $this;
    }


    public function getPrice(): ?string
    {
        return $this->Price;
    }

    public function setPrice(string $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getSupplier(): ?string
    {
        return $this->Supplier;
    }

    public function setSupplier(string $Supplier): self
    {
        $this->Supplier = $Supplier;

        return $this;
    }
}

src/Controller/ShoesController.php
<?php

namespace App\Controller;

use App\Entity\Shoes;
use App\Form\ShoesCreateType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

    class ShoesController extends AbstractController
    {
        /**
         * @Route("/shoes", name="shoes_list")
         */
        public function listAction()
        {
            $shoes = $this->getDoctrine()
                ->getRepository(Shoes::class)
                ->findAll();
            return $this->render('shoes/index.html.twig', [
                'shoes' => $shoes
            ]);
        }
        /**
         * @Route("/shoes/view/{id}", name="shoes_view")
         */
        public function viewAction($id)
        {
            $shoes = $this->getDoctrine()
                ->getRepository(Shoes::class)
                ->find($id);

            return $this->render('shoes/view.html.twig', [
                'shoes' => $shoes
            ]);
        }
        /**
         * @Route("/shoes/delete/{id}", name="shoes_delete")
         */
        public function deleteAction($id)
        {
            $em = $this->getDoctrine()->getManager();
            $shoes = $em->getRepository(shoes::class)->find($id);
            $em->remove($shoes);
            $em->flush();

            $this->addFlash(
                'error',
                'Shoes delete success'
            );

            return $this->redirectToRoute("shoes_list");
        }
        /**
         * @Route("/shoes/create", name="shoes_create", methods={"GET","POST"})
         */
        public function createAction(Request $request)
        {
            $shoes = new shoes();
            $form = $this->createForm(ShoesCreateType::class, $shoes);

            if ($this->saveChanges($form, $request, $shoes)) {
                $this->addFlash(
                    'notice',
                    'Shoes add success'
                );

                return $this->redirectToRoute("shoes_list");
            }

            return $this->render('shoes/create.html.twig', [
                'form' => $form->createView()
            ]);
        }

        public function saveChanges($form, $request, $shoes)
        {
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {

                $em = $this->getDoctrine()->getManager();
                $em->persist($shoes);
                $em->flush();

                return true;
            }
            return false;
        }

        /**
         * @Route("/shoes/update/{id}", name="shoes_update")
         */
        public function updateAction($id, Request $request)
        {
            $em = $this->getDoctrine()->getManager();
            $shoes = $em->getRepository(Shoes::class)->find($id);

            $form = $this->createForm(ShoesCreateType::class, $shoes);

            if ($this->saveChanges($form, $request, $shoes)) {
                $this->addFlash(
                    'notice',
                    'Shoes update success'
                );
                return $this->redirectToRoute('shoes_list');
            }

            return $this->render('shoes/update.html.twig', [
                'form' => $form->createView()
            ]);
        }


    }

templates/shoes/create.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    {{ form_start(form) }}
    <div class="form-group">
        <label for="name">Name:</label>
        {{ form_widget(form.name,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Task name'
            }
        }) }}
        <div class="invalid-feedback">
            {{ form_errors(form.name) }}
        </div>
    </div>
    <div class="form-group">
        <label for="category">Category:</label>
        {{ form_widget(form.category,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Category name'
            }
        }) }}
    </div>

        <div class="form-group">
            <label for="description">Supplier:</label>
            {{ form_widget(form.Supplier,{
                'attr':{
                    'class':'form-control',
                    'placeholder': 'supplier'
                }
            }) }}
        </div>

    <div class="form-group">
        <label for="description">Price:</label>
        {{ form_widget(form.price,{
            'attr':{
                'class':'form-control',
                'placeholder': 'price'
            }
        }) }}
    </div>



    <input type="submit" name="create_shoes" value="Create" class="btn btn-primary"/>
    {{ form_end(form) }}
{% endblock %}

templates/shoes/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="bs-example" data-example-id="striped-table">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Shoes</th>
                <th>Category</th>
                <th>Supplier</th>
                <th>Price</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for shoes in shoes %}
                <tr>
                    <th scope="row">{{ shoes.id }}</th>
                    <td>{{ shoes.name }}</td>
                    <td>{{ shoes.Category }}</td>
                    <td>{{ shoes.supplier }}</td>
                    <td>{{ shoes.price }}</td>
                    <td>
                        <a href="{{ path('shoes_view', {'id': shoes.id}) }} " class='btn btn-success'>View</a>
                        <a href="{{ path('shoes_update', {'id': shoes.id}) }}" class='btn btn-default'>Update</a>
                        <a href="{{ path('shoes_delete', {'id': shoes.id}) }}" class='btn btn-danger'>Delete</a>


                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <a href="{{ path('shoes_create') }}" class="btn btn-primary">Create new</a>
{% endblock %}

templates/shoes/update.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {{ form_start(form) }}
    <div class="form-group">
        <label for="name">Name:</label>
        {{ form_widget(form.name,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Task name'
            }
        }) }}
    </div>
    <div class="form-group">
        <label for="category">Category:</label>
        {{ form_widget(form.category,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Category name'
            }
        }) }}
    </div>
    <div class="form-group">
        <label for="Supplier">Supplier:</label>
        {{ form_widget(form.Supplier,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Supplier name'
            }
        }) }}
    </div>
    <div class="form-group">
        <label for="description">Price:</label>
        {{ form_widget(form.price,{
            'attr':{
                'class':'form-control',
                'placeholder': 'price'
            }
        }) }}
    </div>


    <input type="submit" name="Update_Shoes" value="Update" class="btn btn-primary"/>
    {{ form_end(form) }}
{% endblock %}

templates/shoes/view.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <a href="{{ path('shoes_list') }}" class="btn btn-default">Back to Shoes List</a>
    <hr/>
    <h2 class="page-header">{{ shoes.name }}</h2>
    <ul class="list-group">
        <li class="list-group-item">Category: {{ shoes.category }}</li>
        <li class="list-group-item">Supplier: {{ shoes.supplier }}</li>
        <li class="list-group-item">Price: {{ shoes.price }}</li>

    </ul>

{% endblock %}